version: 1
disable_existing_loggers: False

formatters:
  full:
    format: "%(asctime)s [%(levelname)8s] %(name)s : %(message)s (%(filename)s:%(lineno)s)"
    datefmt: "%Y-%m-%d %H:%M:%S %z"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: full
    stream: ext://sys.stdout
  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: full
    filename: logs/debug.log
    maxBytes: 1048576 # 1MB
    backupCount: 10
    encoding: utf8

loggers:
  __main__:
    level: DEBUG
    handlers: [console, debug_file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, debug_file_handler]
